version: '3.8'


services:
  hufs-reservation-db:
    image: mysql:8.3
    platform: linux/amd64
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "service-db"
      MYSQL_USER: "hwangbbang"
      MYSQL_PASSWORD: "1234"
      LC_ALL: C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - ./study-room-reservation-system/mysql/init.d:/docker-entrypoint-initdb.d

  hufs-reservation-redis:
    image: redis:7.2.5
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "6379:6379"

  hufs-reservation-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - platform=linux/amd64
    image: service_build_image:latest
    ports:
      - "8080:8080"
    depends_on:
      - hufs-reservation-db
      - hufs-reservation-redis
    restart: unless-stopped
    command: [ "java", "-jar", "app.jar" ]
    environment:
      SPRING_DATASOURCE_PASSWORD: "1234"
      SPRING_DATASOURCE_URL: "jdbc:mysql://hufs-reservation-db:3306/service-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
      SPRING_DATASOURCE_USERNAME: "hwangbbang"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_REDIS_HOST: hufs-reservation-redis
      SPRING_REDIS_PORT: 6379