version: '3.8'

services:
  hufs-reservation-db:
    image: mysql:8.3
    platform: linux/amd64
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "hufs-reservation-service-db"
      MYSQL_USER: "hwangbbang"
      MYSQL_PASSWORD: "1234"
      LC_ALL: "C.UTF-8"
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    networks:
      - hwangbbang_network

  hufs-reservation-service:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - platform=linux/amd64
    image: service_build_image:latest
    ports:
      - "8080:8080"
    depends_on:
      - hufs-reservation-db
    networks:
      - hwangbbang_network
    restart: unless-stopped
    environment:
      SERVICE_DB_HOST: hufs-reservation-db
      SERVICE_DB_USER: hwangbbang
      SERVICE_DB_PASSWORD: "1234"
      SERVICE_DB_NAME: "hufs-reservation-service-db"
      TZ: "Asia/Seoul"

networks:
  hwangbbang_network:
    driver: bridge
