version: '3.8'


services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: "service-db"
      LC_ALL: C.UTF-8
    ports:
      - "3306:3306"
#    volumes:
#      - ./study-room-reservation-system/mysql/init.d:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.2.5
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - platform=linux/amd64
    image: service_build_image:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    command: [ "java", "-jar", "app.jar" ]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/service-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_JWT_SECRET: b98f37cbf7fb4beeb4fec0e1a1dfa7b5a86c2f3504441ad6dc8e7b636ad67a80
      SPRING_MAIL_USERNAME: hwangbbang9@gmail.com
      SPRING_MAIL_PASSWORD: crta nqkq kkcy msow
      SPRING_PROFILES_ACTIVE: prod
