server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/service-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: false
        open-in-view: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true # SQL을 보기 좋게 포맷팅
    jwt: # openssl rand -hex 32 ( HS256 )
        secret: b98f37cbf7fb4beeb4fec0e1a1dfa7b5a86c2f3504441ad6dc8e7b636ad67a80
        header: Authorization
        access:
            expiration: 604800000  # 7일 (ms)
            category: access # jwt 의 헤더

        refresh:
            expiration: 7776000000 # 90일 (ms)
            category: refresh # jwt 의 헤더

        password-reset:
            expiration: 600000 # 10분 (ms)
            category: password-reset
    sql:
        init:
            mode: always
            encoding: utf-8

    data:
        redis:
            host: localhost
            port: 6379
    service:
        allowedStartMinute : 15
        allowedEndMinute : 15
        randomChars : "abcdefghjkmnopqrstuvwxyz23456789"
        otpLength : 8
        otpTTL : 300
        noShowCntMonth : 1
        noShowLimit : 10
        reservationLimit : 1
        reservationLimitToday : 2
    mail:
        host: smtp.gmail.com
        port: 587
        username: hwangbbang9@gmail.com
        password: crta nqkq kkcy msow # todo .env 로 빼기
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true


    flyway:
        enabled: true
        baseline-on-migrate: true
        baseline-version: 1
        url: jdbc:mysql://localhost:3306/service-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        user: root
        password: 1234



logging:
    level:
        com:
            test:
                studyroomreservationsystem:
#                    security:
#                            TRACE
#                    apicontroller:
#                            TRACE
                    service:
                        impl: TRACE

#        org:
#            springframework: DEBUG
#                security: DEBUG
