spring:
    datasource:
        url: jdbc:mysql://hufs-reservation-db:3306/hufs-reservation-service-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: "hwangbbang"
        password: "1234"
        driver-class-name: com.mysql.cj.jdbc.Driver

    profiles:
        active:
            info
    jpa:
        show-sql: true
        open-in-view: true
        properties:
            hibernate:
                ddl-auto: create # 배포시 변경해야함
                format_sql: true # SQL을 보기 좋게 포맷팅
#    flyway:
#        enabled: true
#        baseline-on-migrate: true
#        baseline-version: 1
#        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/hufs_reservation
#        user: root
#        password: 1234
