server:
    port: 8080
spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    data:
        redis:
            host: ${SPRING_REDIS_HOST}
            port: ${SPRING_REDIS_PORT}
    service:
        allowedStartMinute: 15
        otpTTL: 300
        noShowBlockMonth : 1
        noShowLimit : 3
        reservationLimitCurrent : 1
        reservationLimitToday : 2
        authCodeExpiryTime : 5

    jpa:
        show-sql: false
        properties:
            hibernate:
#                dialect: org.hibernate.dialect.MySQLDialect
    jwt: # openssl rand -hex 32 ( HS256 )
        header: Authorization
        access:
            secret: ${SPRING_JWT_ACCESS_SECRET}
            expiration: 604800000  # 7일 -> ms
            category: access # jwt 의 헤더

        refresh:
            secret: ${SPRING_JWT_REFRESH_SECRET}
            expiration: 7776000000 # 90일 -> ms
            category: refresh # jwt 의 헤더

        password-reset:
            secret: ${SPRING_JWT_PASSWORD_RESET_SECRET}
            expiration: 600000 # 10분 (ms)
            category: password-reset

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${SPRING_MAIL_USERNAME}
        password: ${SPRING_MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true

    flyway:
        enabled: true
        baseline-on-migrate: true
        baseline-version: 0
        url: ${SPRING_DATASOURCE_URL}
        user: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
env:
    base-url: ${SPRING_BASE_URL}
    api-version: 2.6.14

#logging:
#    level:
#        org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl: TRACE  # 커넥션 반환 로그 확인