server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/service-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: 1234

        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: true
        open-in-view: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true # SQL을 보기 좋게 포맷팅
    sql:
        init:
            mode: always
            encoding: utf-8
    jwt: # openssl rand -hex 32 ( HS256 )
        secret: b98f37cbf7fb4beeb4fec0e1a1dfa7b5a86c2f3504441ad6dc8e7b636ad67a80

        access:
            expiration: 604800000  # 7일 -> ms
#            header: Authorization

        refresh:
            expiration: 7776000000 # 90일 -> ms
#            header: Authorization-refresh

#    flyway:
#        enabled: true
#        baseline-on-migrate: true
#        baseline-version: 1
#        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/hufs_reservation
#        user: root
#        password: 1234

logging:
    level:
        com:
            test:
                studyroomreservationsystem:
                    security:
                        jwt:
                            TRACE
#                    apicontroller:
#                        auth:
#                            TRACE

        org:
            springframework:
                security: TRACE

